f1 = input("ENter the fruit name")
f2 = input("ENter the fruit name")
f3 = input("ENter the fruit name")
f4 = input("ENter the fruit name")
f5 = input("ENter the fruit name")
f6 = input("ENter the fruit name")
f7 = input("ENter the fruit name")
list = (f1, f2, f3, f4, f5, f6, f7)
print(list)
